fix(ci): always run the done stage but check the previous stages are not failed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -118,10 +118,19 @@
             ghcr.io/gh-org-template/kong-openssl:${{ needs.release.outputs.release-git-tag }}-linux-gnu \
             ghcr.io/gh-org-template/kong-openssl:${{ needs.release.outputs.release-git-tag }}-linux-musl
           docker manifest push ghcr.io/gh-org-template/kong-openssl:${{ needs.release.outputs.release-git-tag }}
+
     done:
-      needs: [artifacts]
+      needs: [release, artifacts, multi-arch]
       name: Done
-      if: needs.artifacts.result == 'success'
+      if: always()
       runs-on: ubuntu-latest
       steps:
+      - name: Check for Failed Jobs
+        run: |
+          if [[ "${{ needs.release.result }}" == "failure" || "${{ needs.artifacts.result }}" == "failure" || "${{ needs.multi-arch.result }}" == "failure" ]]; then
+            echo "One or more jobs failed. Marking release as failed."
+            exit 1
+          else
+            echo "All jobs succeeded or were skipped. Marking release as successful."
+          fi
       - run: echo 'done'
